const List<String> categories = [
  'Pesticides',
  'Organic additives',
  'Fertilizers',
  'Tools and machinery',
  'Seeds',
];

const Map<String, List<Map<String, String>>> products = {
  'Pesticides': [
    {'name': 'Neem Oil', 'image': 'assets/images/bug-off.svg'},
    {'name': 'Bio Insecticide', 'image': 'assets/images/bug.svg'},
    {'name': 'Pheromone Trap', 'image': 'assets/images/info-circle.svg'},
    {'name': 'Fungal Control', 'image': 'assets/images/leaf.svg'},
    {'name': 'Mite Control', 'image': 'assets/images/bug-off.svg'},
    {'name': 'Larvicide', 'image': 'assets/images/bug.svg'},
    {'name': 'Organic Spray', 'image': 'assets/images/droplet.svg'},
    {'name': 'Crop Shield', 'image': 'assets/images/plant.svg'},
    {'name': 'Field Sanitizer', 'image': 'assets/images/info-circle.svg'},
  ],
  'Organic additives': [
    {'name': 'Compost', 'image': 'assets/images/leaf.svg'},
    {'name': 'Vermicompost', 'image': 'assets/images/plant-2.svg'},
    {'name': 'Seaweed Extract', 'image': 'assets/images/droplet.svg'},
    {'name': 'Bio Stimulant', 'image': 'assets/images/plant.svg'},
    {'name': 'Molasses', 'image': 'assets/images/droplet.svg'},
    {'name': 'Humic Acid', 'image': 'assets/images/leaf.svg'},
    {'name': 'Amino Acid', 'image': 'assets/images/plant.svg'},
    {'name': 'Organic Booster', 'image': 'assets/images/plant-2.svg'},
    {'name': 'Microbes Mix', 'image': 'assets/images/info-circle.svg'},
  ],
  'Fertilizers': [
    {'name': 'NPK 19:19:19', 'image': 'assets/images/leaf.svg'},
    {'name': 'Urea', 'image': 'assets/images/info-circle.svg'},
    {'name': 'DAP', 'image': 'assets/images/info-circle.svg'},
    {'name': 'Potash', 'image': 'assets/images/leaf.svg'},
    {'name': 'Calcium Nitrate', 'image': 'assets/images/droplet.svg'},
    {'name': 'Magnesium Sulphate', 'image': 'assets/images/droplet.svg'},
    {'name': 'Bio Fertilizer', 'image': 'assets/images/plant.svg'},
    {'name': 'Soil Conditioner', 'image': 'assets/images/plant-2.svg'},
    {'name': 'Micronutrient Mix', 'image': 'assets/images/info-circle.svg'},
  ],
  'Tools and machinery': [
    {'name': 'Tractor', 'image': 'assets/images/tractor.svg'},
    {'name': 'Sprayer', 'image': 'assets/images/droplet.svg'},
    {'name': 'Plough', 'image': 'assets/images/shovel.svg'},
    {'name': 'Harvester', 'image': 'assets/images/leaf.svg'},
    {'name': 'Seeder', 'image': 'assets/images/plant.svg'},
    {'name': 'Cultivator', 'image': 'assets/images/plant-2.svg'},
    {'name': 'Shovel', 'image': 'assets/images/shovel.svg'},
    {'name': 'Hoe', 'image': 'assets/images/shovel.svg'},
    {'name': 'Rake', 'image': 'assets/images/leaf.svg'},
  ],
  'Seeds': [
    {'name': 'Wheat Seeds', 'image': 'assets/images/plant.svg'},
    {'name': 'Rice Seeds', 'image': 'assets/images/plant-2.svg'},
    {'name': 'Corn Seeds', 'image': 'assets/images/leaf.svg'},
    {'name': 'Barley Seeds', 'image': 'assets/images/leaf.svg'},
    {'name': 'Soybean Seeds', 'image': 'assets/images/plant.svg'},
    {'name': 'Pea Seeds', 'image': 'assets/images/plant-2.svg'},
    {'name': 'Sunflower Seeds', 'image': 'assets/images/sun.svg'},
    {'name': 'Cotton Seeds', 'image': 'assets/images/leaf.svg'},
    {'name': 'Sorghum Seeds', 'image': 'assets/images/leaf.svg'},
  ],
};